acme/urls.py
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin
#from django.urls import path

from . import views

handler404='acme.views.handler404'
handler500='acme.views.handler500'


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from . import views

app_name='blog'
urlpatterns = [
    url('^$', views.index, name='index'),
    url('^toto', views.toto, name='toto'),
    url('^posts/(?P<id>[0-9]+)', views.show, name='show'),
#	ca fonctionne si je met p a la place de posts
#   url('^p/(?P<id>[0-9]+)', views.show, name='show'),
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
	title=models.CharField(max_length=255)
	body=models.TextField()

	def __str__(self):
		return self.title

acme/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def home(request):
	#return HttpResponse('<h1>Hello Acme</h1>')
	return render(request, 'home.html')

def about(request):
	return render(request, 'pages/about.html')

def contact(request):
	return render(request, 'pages/contact.html')

def handler404(request, exception):
	return render(request, 'errors/404.html', {'error':exception}, status=404)
#	return render(request, 'errors/404.html', {}, status=404)

def handler500(request, exception=None):
	return render(request, 'errors/500.html', {'error':exception}, status=500)

blog/views.py
from django.shortcuts import render

from .mocks import Posters

#posters=[
#	{'id':1,'title':'Mon roi','body':'Livre du roi'},
#	{'id':2,'title':'Ma Reine','body':'Livre de la Reine'},
#	{'id':3,'title':'Mon Singe','body':'Livre du singe'},
#]

# Create your views here.
def index(request):
	posts=['First Post', 'Second Post', 'Third Post']
	return render(request, 'blog/index.html', {'toto': posts})

def toto(request):
	posterVide=[]
	posters=Posters.all()
	return render(request, 'blog/toto.html', {'posterEnvoye':posters, 'posterVide':posterVide})

def show(request, id):
	posters=Posters.find(id)
	return render(request, 'blog/show.html',{'post':posters})

blog/templates/blog/index.html
{% extends 'layouts/base.html' %}

{%block title %}Homepage | blog{% endblock %}

{%block content %}
<h1>blog</h1>

{{toto}}

<ul>
{% for to in toto %}
<li>{{to}}</li>
{% endfor %}
</ul>


{% for to in toto %}
<ul>
	<li>{{to}}</li>
</ul>
{% endfor %}

{% endblock %}

blog/templates/blog/show.html
{% extends 'layouts/base.html' %}

{%block title %}Blog | {{post.title}}{% endblock %}

{%block content %}
<article>
	<h1>#{{post.id}} - {{post.title}}</h1>
	<p>{{post.body}}</p>
</article>

<hr>
<p><a href="{% url 'blog:toto' %}">All posts</a></p>

{% endblock content %}

blog/templates/blog/toto.html
{% extends 'layouts/base.html' %}

{%block content %}

	<h1>toto({{posterEnvoye|length}})</h1>

	{{posterEnvoye}}

	{% for po in posterEnvoye %}
	<ul>
	<li>{{po}}</li>
	</ul>
	{% endfor %}

	<br/>
	<br/>

	{% for po in posterEnvoye %}
		<article>
		<h2><a href="{% url 'blog:show' id=po.id %}">#{{po.id}}-{{po.title|upper}}</a></h2>

		<p>{{po.body|truncatewords:2}}</p>

		<p><a href="{% url 'blog:show' id=po.id %}">lire la suite</a></p>
		</article>

		{% if forloop.counter %}
		<p>au compteur</p>
		{% endif %}

		{% if forloop.counter0 %}
		<p>au compteur 0</p>
		{% endif %}

		{% if forloop.first %}
		<p>1er</p>
		{% endif %}

		{% if not forloop.last %}
		<hr>
		{% endif %}

	{% endfor %}

	{% for po in posterVide %}
	<p>{{po.id}}</p>

	{%empty%}
	<p>sorry it s empty</p>

	{% endfor %}

{% endblock %}

templates/home.html
{% extends 'layouts/base.html' %}

{%block title %}Homepage | Acme{% endblock %}

{%block content %}
<h1>Hello World</h1>

<p><a href="{% url 'blog:index' %}">Visiter notre blog</a></p>
<p><a href="{% url 'blog:toto' %}">Voir nos liens notre blog</a></p>
{% endblock %}

templates/layouts/_nav.html
<ul>
	<li><a href="{% url 'home' %}">Home</li>
	<li><a href="{% url 'about' %}">About</li>
	<li><a href="{% url 'contact' %}">Contact</li>
	<li><a href="{% url 'blog:index' %}">Blog</li>
	<li><a href="{% url 'blog:toto' %}">Toto</li>
</ul>

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Acme{% endblock%}</title>
</head>
	<body>
{% include 'layouts/_nav.html' %}

{%block content %}Toto{% endblock %}
	</body>
	</html>

templates/pages/about.html
{% extends 'layouts/base.html' %}

{%block title %}About{% endblock %}

{%block content %}

<h1>About</h1>

{% endblock %}

templates/pages/contact.html
{% extends 'layouts/base.html' %}

{%block title %}Contact{% endblock %}

{%block content %}

<h1>Contact</h1>

{% endblock %}